pca:
  n_components: 256
  random_state: 42
  scale: true
  
model:
  id_col: id
  target_col: price
  test_size: 0.2
  random_state: 42

xgboost:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8

